[package]
name = "lobster"
version = "0.0.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.19", features = ["full"] }
tokio = { version = "1.19.2", features = ["full"] }
juniper = { version = "0.15.9" }
juniper_hyper = { version = "0.8.0" }