name = 'lobster'
main = 'build/esbuild/worker/index@5IVCORJT.js'
account_id = ''
workers_dev = false
usage_model = 'bundled'
routes = []
r2_buckets = []
compatibility_date = '2022-05-30'
[triggers]
crons = []

[[kv_namespaces]]
binding = 'STATIC_CONTENT'
id = '36715eb5935948dcaeefd682d9cf8897'
preview_id = 'eb6cec9ba9944589946a2fb13677e672'

[durable_objects]
bindings = []

[env]
compatibility_date = '2022-05-30'
compatibility_flags = ['streams_enable_constructors']

[build]
command = 'go run esbuild/main.go'
cwd = '.'
watch_dir = 'build'

