name = 'lobster'
main = ''
account_id = ''
workers_dev = false
usage_model = 'bundled'
routes = []
compatibility_date = '2022-05-30'
compatibility_flags = ['streams_enable_constructors']
[triggers]
crons = []

[env]
[env.dev]
main = 'worker/entry/csr.tsx'
r2_buckets = []
[[env.dev.kv_namespaces]]
binding = 'STATIC_CONTENT'
id = '36715eb5935948dcaeefd682d9cf8897'
preview_id = 'eb6cec9ba9944589946a2fb13677e672'

[env.dev.durable_objects]
bindings = []

[env.dev.vars]
GRAPHQL_ENDPOINT = 'http://localhost:8787/'
MODE = 'development'


[env.prod]
main = 'build/esbuild/worker/entry/ssr@ZSALGZFR.js'
r2_buckets = []
[[env.prod.kv_namespaces]]
binding = 'STATIC_CONTENT'
id = '36715eb5935948dcaeefd682d9cf8897'
preview_id = 'eb6cec9ba9944589946a2fb13677e672'

[env.prod.durable_objects]
bindings = []

[env.prod.vars]
GRAPHQL_ENDPOINT = 'https://aegooby.workers.dev/'
MODE = 'production'



[build]
command = ''
cwd = '.'
watch_dir = 'build'

