[package]
name = "seagull-server"
version = "0.0.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "seagull"
path = "main.rs"
test = true
doctest = true
bench = true
doc = true
plugin = false
proc-macro = false
harness = true
edition = "2021"
required-features = []

[dependencies]
anyhow = { version = "1.0.58" }
axum = { version = "0.5.9", features = ["http1", "http2", "json", "matched-path", "original-uri", "query", "tower-log", "ws"] }
chrono = { version = "0.4.19" }
dataloader = { version = "0.15.0", default-features = false, features = ["runtime-tokio"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "uuid"] }
dotenv = { version = "0.15.0" }
hyper = { version = "0.14.19", features = ["full"] }
juniper = { version = "0.15.9" }
juniper_hyper = { version = "0.8.0" }
mime = { version = "0.3.16" }
mime_guess = { version = "2.0.4" }
tokio = { version = "1.19.2", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["io"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["full"] }
tracing = { version = "0.1.35" }
tracing-subscriber = { version = "0.3.11" }
uuid = { version = "0.6.0", features = ["serde", "v4"] }

[features]
default = []
dev = []
prod = []
all = ["dev", "prod"]
