[package]
name = "seagull-server"
version = "0.0.0"
edition = "2021"

# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "seagull"
path = "main.rs"
test = true
doctest = true
bench = true
doc = true
plugin = false
proc-macro = false
harness = true
edition = "2021"
required-features = []

[dependencies]
anyhow = { version = "1.0.58" }
async-trait = { version = "0.1.56" }
bytes = { version = "1.1.0" }
chrono = { version = "0.4.19" }
dataloader = { version = "0.15.0", default-features = false, features = ["runtime-tokio"] }
deno_core = { version = "0.139.0" }
deno_runtime = { version = "0.65.0" }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "uuid"] }
dotenv = { version = "0.15.0" }
hyper = { version = "0.14.19", features = ["full"] }
juniper = { version = "0.15.9" }
juniper_hyper = { version = "0.8.0" }
lazy_static = { version = "1.4.0" }
mime = { version = "0.3.16" }
mime_guess = { version = "2.0.4" }
tokio = { version = "1.19.2", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["io"] }
uuid = { version = "0.6.0", features = ["serde", "v4"] }

[features]
default = []
dev = []
prod = []
all = ["dev", "prod"]
